FROM openjdk:14.0.2-jdk-oracle

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    JAVA_OPTS="" \
    SPRING_PROFILES_ACTIVE="" \
    HOST_NAME="" 

VOLUME /tmp
COPY ./build/libs/config-server-*.jar app.jar

ADD entrypoint.sh entrypoint.sh
RUN chmod 755 entrypoint.sh && chown root entrypoint.sh
USER root

ENTRYPOINT ["./entrypoint.sh"]

EXPOSE 8080

